sonar.projectKey=Shway95_spring-microservice-cicd
sonar.organization=shway95
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=build/classes
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
